image: gradle:7.3.3-jdk17-alpine

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # Custom CI postgres settings
  SPRING_PROPS_POSTGRES_HOST: postgres
  SPRING_PROPS_POSTGRES_PORT: 5432
  # General CI postgres settings
  POSTGRES_DB: oopp
  POSTGRES_USER: oopp_admin
  POSTGRES_PASSWORD: "1234"
  POSTGRES_HOST_AUTH_METHOD: trust

services:
  - postgres

stages:
  - build
  - analysis
  - test

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble

checkstyle-main:
  stage: analysis
  script: ./gradlew checkstyleMain
  cache:
    key: "$CI_COMMIT_REF_NAME-main"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

checkstyle-test:
  stage: analysis
  script: ./gradlew checkstyleTest
  cache:
    key: "$CI_COMMIT_REF_NAME-test"
    policy: pull
    paths:
      - build/
      - .gradle/
  allow_failure: true

test:
  stage: test
  script:
    - ./gradlew AggregateJacocoReport
    # preserve coverage information in an easy-to-reach folder
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/"`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/