version: '3.8'

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=40000'
    environment:
      - POSTGRES_USER=oopp_admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=oopp
    ports:
      - "${SPRING_PROPS_POSTGRES_PORT:-5555}:5432"
