jwt:
  secret: L4IbsorCm0RZQy5Fokc9leeK4tMWhm2Isw1oMLVV

management:
  server:
    address: "127.0.0.1"
    port: 11004
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

spring:
  application:
    name: quizzz
  sql:
    init:
      platform: postgres
      mode: always
  datasource:
    url: jdbc:postgresql://${SPRING_PROPS_POSTGRES_HOST:localhost}:${SPRING_PROPS_POSTGRES_PORT:5555}/oopp
    username: oopp_admin
    password: 1234
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 256
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      jdbc:
        lob:
          non_contextual_creation: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    server: ${QUIZZZ_LOG_LEVEL:DEBUG}
