jwt:
  secret: L4IbsorCm0RZQy5Fokc9leeK4tMWhm2Isw1oMLVV

spring:
  application:
    name: quizzz
  datasource:
    url: jdbc:h2:file:./quizzzz
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect